// O'zbekistondagi oliy ta'lim muassasalari (davlat, nodavlat va xorijiy filiallar).
// Manba: oliygoh.uz OTM katalogi va litsenziyaga ega nodavlat OTMlar ro'yxati (2026-10), qo'shimcha xorijiy filiallar.
// Ro'yxatda yo'q oliygohni foydalanuvchi qo'lda yozadi (profiles.university_name).

export type UniversityType = "davlat" | "nodavlat";

export type University = { id: string; name: string; type: UniversityType; region: string };

export const REGIONS = [
  "Toshkent shahri",
  "Toshkent viloyati",
  "Andijon",
  "Buxoro",
  "Farg'ona",
  "Jizzax",
  "Xorazm",
  "Namangan",
  "Navoiy",
  "Qashqadaryo",
  "Qoraqalpog'iston",
  "Samarqand",
  "Sirdaryo",
  "Surxondaryo",
] as const;

const u = (id: string, name: string, type: UniversityType, region: string): University => ({ id, name, type, region });

export const UNIVERSITIES: University[] = [
  u("akfa-universiteti", "Akfa universiteti", "nodavlat", "Toshkent shahri"),
  u("alfraganus-university", "Alfraganus University", "nodavlat", "Toshkent shahri"),
  u("binary-international-university", "Binary international university", "nodavlat", "Toshkent shahri"),
  u("botir-zokirov-nomidagi-milliy-estrada-sanati-instituti", "Botir Zokirov nomidagi Milliy estrada san'ati instituti", "davlat", "Toshkent shahri"),
  u("british-management-university", "British Management University", "nodavlat", "Toshkent shahri"),
  u("cambridge-international-university", "Cambridge International University", "nodavlat", "Toshkent shahri"),
  u("capital-school-innovatsion-va-ijtimoiy-iqtisodiyot-universit", "Capital School - Innovatsion va ijtimoiy-iqtisodiyot universiteti", "nodavlat", "Toshkent shahri"),
  u("central-asian-medical-university", "Central Asian Medical university", "nodavlat", "Toshkent shahri"),
  u("central-asian-university", "Central Asian University", "nodavlat", "Toshkent shahri"),
  u("colligium-humanum-varshava-menejment-universiteti", "Colligium Humanum Varshava menejment universiteti", "nodavlat", "Toshkent shahri"),
  u("cyber-university-davlat-universiteti", "Cyber university\" davlat universiteti", "davlat", "Toshkent shahri"),
  u("digital-university", "Digital University", "nodavlat", "Toshkent shahri"),
  u("diplomat-university", "Diplomat University", "nodavlat", "Toshkent shahri"),
  u("european-medical-university", "European medical University", "nodavlat", "Toshkent shahri"),
  u("farmatsevtika-talim-va-tadqiqot-instituti", "Farmatsevtika ta'lim va tadqiqot instituti", "nodavlat", "Toshkent shahri"),
  u("g-v-plexanov-nomidagi-rossiya-iqtisodiyot-universitetining-t", "G.V. Plexanov nomidagi Rossiya iqtisodiyot universitetining Toshkent filiali", "nodavlat", "Toshkent shahri"),
  u("geologiya-fanlari-universiteti", "Geologiya fanlari universiteti", "davlat", "Toshkent shahri"),
  u("i-m-gubkin-nomidagi-rossiya-davlat-neft-va-gaz-universitetin", "I.M. Gubkin nomidagi Rossiya davlat neft va gaz universitetining Toshkent filiali", "nodavlat", "Toshkent shahri"),
  u("impuls-tibbiyot-instituti", "Impuls tibbiyot instituti", "nodavlat", "Toshkent shahri"),
  u("international-school-of-finance-and-technology", "International school of finance and technology", "nodavlat", "Toshkent shahri"),
  u("iqtisodiyot-va-pedagogika-universiteti", "Iqtisodiyot va pedagogika universiteti", "nodavlat", "Toshkent shahri"),
  u("islom-karimov-nomidagi-toshkent-davlat-texnika-universiteti", "Islom Karimov nomidagi Toshkent davlat texnika universiteti", "davlat", "Toshkent shahri"),
  u("it-park-university", "IT-Park University", "nodavlat", "Toshkent shahri"),
  u("jahon-iqtisodiyoti-va-diplomatiya-universiteti", "Jahon iqtisodiyoti va diplomatiya universiteti", "davlat", "Toshkent shahri"),
  u("jamoat-xavfsizligi-universiteti", "Jamoat xavfsizligi universiteti", "davlat", "Toshkent shahri"),
  u("japan-digital-university", "Japan Digital University", "nodavlat", "Toshkent shahri"),
  u("kamoliddin-behzod-nomidagi-milliy-rassomlik-va-dizayn-instit", "Kamoliddin Behzod nomidagi Milliy rassomlik va dizayn instituti", "davlat", "Toshkent shahri"),
  u("kimyo-international-university-in-tashkent", "Kimyo International University in Tashkent", "nodavlat", "Toshkent shahri"),
  u("m-v-lomonosov-nomidagi-moskva-davlat-universitetining-toshke", "M.V. Lomonosov nomidagi Moskva davlat universitetining Toshkent filiali", "nodavlat", "Toshkent shahri"),
  u("mamun-universiteti", "Ma'mun universiteti", "nodavlat", "Toshkent shahri"),
  u("mehnat-va-ijtimoiy-munosabatlar-akademiyasi", "Mehnat va ijtimoiy munosabatlar akademiyasi", "nodavlat", "Toshkent shahri"),
  u("mei-milliy-tadqiqot-universitetining-toshkent-filiali", "MEI\" Milliy tadqiqot universitetining Toshkent filiali", "nodavlat", "Toshkent shahri"),
  u("millat-umidi-university", "Millat Umidi University", "nodavlat", "Toshkent shahri"),
  u("mirzo-ulugbek-nomidagi-ozbekiston-milliy-universiteti", "Mirzo Ulug'bek nomidagi O'zbekiston Milliy universiteti", "davlat", "Toshkent shahri"),
  u("ozbekiston-davlat-jahon-tillari-universiteti", "O'zbekiston davlat jahon tillari universiteti", "davlat", "Toshkent shahri"),
  u("ozbekiston-davlat-jismoniy-tarbiya-va-sport-universiteti", "O'zbekiston davlat jismoniy tarbiya va sport universiteti", "davlat", "Toshkent shahri"),
  u("ozbekiston-davlat-konservatoriyasi", "O'zbekiston davlat konservatoriyasi", "davlat", "Toshkent shahri"),
  u("ozbekiston-davlat-sanat-va-madaniyat-instituti", "O'zbekiston davlat san'at va madaniyat instituti", "davlat", "Toshkent shahri"),
  u("ozbekiston-davlat-xoreografiya-akademiyasi", "O'zbekiston davlat xoreografiya akademiyasi", "davlat", "Toshkent shahri"),
  u("ozbekiston-jurnalistika-va-ommaviy-kommunikatsiyalar-univers", "O'zbekiston jurnalistika va ommaviy kommunikatsiyalar universiteti", "davlat", "Toshkent shahri"),
  u("ozbekiston-milliy-pedagogika-universiteti", "O'zbekiston milliy pedagogika universiteti", "davlat", "Toshkent shahri"),
  u("ozbekiston-respublikasi-bank-moliya-akademiyasi", "O'zbekiston Respublikasi Bank-moliya akademiyasi", "davlat", "Toshkent shahri"),
  u("ozbekiston-respublikasi-huquqni-muhofaza-qilish-akademiyasi", "O'zbekiston Respublikasi Huquqni muhofaza qilish akademiyasi", "davlat", "Toshkent shahri"),
  u("ozbekiston-respublikasi-prezidenti-huzuridagi-davlat-boshqar", "O'zbekiston Respublikasi Prezidenti huzuridagi Davlat boshqaruvi akademiyasi", "davlat", "Toshkent shahri"),
  u("ozbekiston-xalqaro-islomshunoslik-akademiyasi", "O'zbekiston xalqaro islomshunoslik akademiyasi", "davlat", "Toshkent shahri"),
  u("oliy-sport-mahorati-instituti", "Oliy sport mahorati instituti", "davlat", "Toshkent shahri"),
  u("oriental-university", "Oriental University", "nodavlat", "Toshkent shahri"),
  u("osiyo-xalqaro-universiteti", "Osiyo xalqaro universiteti", "nodavlat", "Buxoro"),
  u("oziq-ovqat-texnologiyasi-va-muhandisligi-xalqaro-instituti", "Oziq-ovqat texnologiyasi va muhandisligi xalqaro instituti", "davlat", "Farg'ona"),
  u("pdp-university", "PDP University", "nodavlat", "Toshkent shahri"),
  u("perfect-university", "Perfect University", "nodavlat", "Toshkent shahri"),
  u("profi-university", "Profi University", "nodavlat", "Toshkent shahri"),
  u("ranch-texnologiya-universiteti", "Ranch texnologiya universiteti", "nodavlat", "Toshkent shahri"),
  u("raqamli-iqtisodiyot-va-agrotexnologiyalar-universiteti", "Raqamli iqtisodiyot va agrotexnologiyalar universiteti", "nodavlat", "Toshkent shahri"),
  u("renessans-talim-universiteti", "Renessans ta'lim universiteti", "nodavlat", "Toshkent shahri"),
  u("sabhram-university", "Sabhram university", "nodavlat", "Toshkent shahri"),
  u("sharda-universiteti", "Sharda universiteti", "nodavlat", "Andijon"),
  u("stars-international-university", "Stars International University", "nodavlat", "Toshkent shahri"),
  u("tashkent-international-university-of-education", "Tashkent International University of Education", "nodavlat", "Toshkent shahri"),
  u("team-university", "TEAM University", "nodavlat", "Toshkent shahri"),
  u("tmc-institute", "TMC Institute", "nodavlat", "Toshkent shahri"),
  u("toshkent-amaliy-fanlar-universiteti", "Toshkent Amaliy fanlar universiteti", "nodavlat", "Toshkent shahri"),
  u("toshkent-arxitektura-qurilish-universiteti", "Toshkent arxitektura-qurilish universiteti", "davlat", "Toshkent shahri"),
  u("toshkent-davlat-agrar-universiteti", "Toshkent davlat agrar universiteti", "davlat", "Toshkent shahri"),
  u("toshkent-davlat-iqtisodiyot-universiteti", "Toshkent davlat iqtisodiyot universiteti", "davlat", "Toshkent shahri"),
  u("toshkent-davlat-ozbek-tili-va-adabiyoti-universiteti", "Toshkent davlat o'zbek tili va adabiyoti universiteti", "davlat", "Toshkent shahri"),
  u("toshkent-davlat-sharqshunoslik-universiteti", "Toshkent davlat sharqshunoslik universiteti", "davlat", "Toshkent shahri"),
  u("toshkent-davlat-stomatologiya-instituti", "Toshkent davlat stomatologiya instituti", "davlat", "Toshkent shahri"),
  u("toshkent-davlat-tibbiyot-universiteti", "Toshkent davlat tibbiyot universiteti", "davlat", "Toshkent shahri"),
  u("toshkent-davlat-transport-universiteti", "Toshkent davlat transport universiteti", "davlat", "Toshkent shahri"),
  u("toshkent-davlat-yuridik-universiteti", "Toshkent Davlat Yuridik Universiteti", "davlat", "Toshkent shahri"),
  u("toshkent-davlat-yuridik-universiteti-ixtisoslashtirilgan-fil", "Toshkent davlat yuridik universiteti Ixtisoslashtirilgan filiali", "davlat", "Toshkent shahri"),
  u("toshkent-farmatsevtika-instituti", "Toshkent farmatsevtika instituti", "davlat", "Toshkent shahri"),
  u("toshkent-iqtisodiyot-va-pedagogika-instituti", "Toshkent Iqtisodiyot va pedagogika instituti", "nodavlat", "Toshkent shahri"),
  u("tiqxmmi", "\"TIQXMMI\" Milliy tadqiqot universiteti (Toshkent irrigatsiya va qishloq xo'jaligini mexanizatsiyalashtirish muhandislari instituti)", "davlat", "Toshkent shahri"),
  u("toshkent-kimyo-texnologiya-instituti", "Toshkent kimyo-texnologiya instituti", "davlat", "Toshkent shahri"),
  u("toshkent-menejment-va-iqtisodiyot-universiteti", "Toshkent menejment va iqtisodiyot universiteti", "nodavlat", "Toshkent shahri"),
  u("toshkent-pediatriya-tibbiyot-instituti", "Toshkent pediatriya tibbiyot instituti", "davlat", "Toshkent shahri"),
  u("toshkent-shahrida-vebster-universiteti", "Toshkent shahrida Vebster universiteti", "nodavlat", "Toshkent shahri"),
  u("toshkent-shahridagi-adju-universiteti", "Toshkent shahridagi ADJU universiteti", "nodavlat", "Toshkent shahri"),
  u("toshkent-shahridagi-amiti-universiteti", "Toshkent shahridagi Amiti universiteti", "nodavlat", "Toshkent shahri"),
  u("toshkent-shahridagi-inha-universiteti", "Toshkent shahridagi Inha universiteti", "nodavlat", "Toshkent shahri"),
  u("toshkent-shahridagi-puchon-universiteti", "Toshkent shahridagi Puchon universiteti", "nodavlat", "Toshkent shahri"),
  u("toshkent-shahridagi-turin-politexnika-universiteti", "Toshkent shahridagi Turin politexnika universiteti", "nodavlat", "Toshkent shahri"),
  u("toshkent-shahridagi-vestminster-xalqaro-universiteti", "Toshkent shahridagi Vestminster xalqaro universiteti", "nodavlat", "Toshkent shahri"),
  u("toshkent-shahridagi-yeodju-texnika-instituti", "Toshkent shahridagi Yeodju texnika instituti", "nodavlat", "Toshkent shahri"),
  u("toshkent-toqimachilik-va-yengil-sanoat-instituti", "Toshkent to'qimachilik va yengil sanoat instituti", "davlat", "Toshkent shahri"),
  u("toshkent-xalqaro-moliyaviy-boshqaruv-va-texnologiyalar-unive", "Toshkent xalqaro moliyaviy boshqaruv va texnologiyalar universiteti", "nodavlat", "Toshkent shahri"),
  u("toshkentdagi-singapur-menejmentni-rivojlantirish-instituti", "Toshkentdagi Singapur menejmentni rivojlantirish instituti", "nodavlat", "Toshkent shahri"),
  u("turan-international-university", "Turan international university", "nodavlat", "Toshkent shahri"),
  u("turkiya-iqtisodiyot-va-texnologiyalar-universitetining-toshk", "Turkiya iqtisodiyot va texnologiyalar universitetining Toshkent shahridagi filiali", "nodavlat", "Toshkent shahri"),
  u("university-of-business-and-science", "University of business and science", "nodavlat", "Toshkent shahri"),
  u("university-of-management-and-future-technologies", "University of management and future technologies", "nodavlat", "Toshkent shahri"),
  u("valley-innovative-university", "Valley Innovative University", "nodavlat", "Toshkent shahri"),
  u("xalqaro-innovatsion-universiteti", "Xalqaro innovatsion universiteti", "nodavlat", "Toshkent shahri"),
  u("xalqaro-nordik-universiteti", "Xalqaro Nordik universiteti", "nodavlat", "Toshkent shahri"),
  u("yangi-asr-universiteti", "Yangi asr universiteti", "nodavlat", "Toshkent shahri"),
  u("yangi-ozbekiston-universiteti", "Yangi O'zbekiston universiteti", "davlat", "Toshkent shahri"),
  u("yunus-rajabiy-nomidagi-ozbek-milliy-musiqa-sanati-instituti", "Yunus Rajabiy nomidagi O'zbek milliy musiqa san'ati instituti", "davlat", "Toshkent shahri"),
  u("andijon-davlat-chet-tillari-instituti", "Andijon davlat chet tillari instituti", "davlat", "Andijon"),
  u("andijon-davlat-pedagogika-instituti", "Andijon davlat pedagogika instituti", "davlat", "Andijon"),
  u("andijon-davlat-texnika-instituti", "Andijon davlat texnika instituti", "davlat", "Andijon"),
  u("andijon-davlat-tibbiyot-instituti", "Andijon davlat tibbiyot instituti", "davlat", "Andijon"),
  u("andijon-davlat-universiteti", "Andijon davlat universiteti", "davlat", "Andijon"),
  u("andijon-iqtisodiyot-va-qurilish-instituti", "Andijon iqtisodiyot va qurilish instituti", "davlat", "Andijon"),
  u("andijon-mashinasozlik-instituti", "Andijon mashinasozlik instituti", "davlat", "Andijon"),
  u("andijon-qishloq-xojaligi-va-agrotexnologiyalar-instituti", "Andijon qishloq xo'jaligi va agrotexnologiyalar instituti", "davlat", "Andijon"),
  u("toshkent-davlat-iqtisodiyot-universiteti-andijon-fakulteti", "Toshkent davlat iqtisodiyot universiteti Andijon fakulteti", "davlat", "Andijon"),
  u("abu-ali-ibn-sino-nomidagi-buxoro-davlat-tibbiyot-instituti", "Abu Ali Ibn Sino nomidagi Buxoro davlat tibbiyot instituti", "davlat", "Buxoro"),
  u("buxoro-davlat-pedagogika-instituti", "Buxoro davlat pedagogika instituti", "davlat", "Buxoro"),
  u("buxoro-davlat-texnika-universiteti", "Buxoro davlat texnika universiteti", "davlat", "Buxoro"),
  u("buxoro-davlat-universiteti", "Buxoro davlat universiteti", "davlat", "Buxoro"),
  u("buxoro-innovatsion-tibbiyot-instituti", "Buxoro innovatsion tibbiyot instituti", "nodavlat", "Buxoro"),
  u("buxoro-innovatsiyalar-universiteti", "Buxoro innovatsiyalar universiteti", "nodavlat", "Buxoro"),
  u("buxoro-muhandislik-texnologiya-instituti", "Buxoro muhandislik-texnologiya instituti", "davlat", "Buxoro"),
  u("buxoro-psixologiya-va-xorijiy-tillar-instituti", "Buxoro psixologiya va xorijiy tillar instituti", "nodavlat", "Buxoro"),
  u("tiqxmmi-mtu-buxoro-tabiiy-resurslarni-boshqarish-instituti", "Tiqxmmi\" Mtu Buxoro Tabiiy Resurslarni Boshqarish Instituti", "davlat", "Buxoro"),
  u("fargona-davlat-texnika-universiteti", "Farg'ona davlat texnika universiteti", "davlat", "Farg'ona"),
  u("fargona-davlat-universiteti", "Farg'ona davlat universiteti", "davlat", "Farg'ona"),
  u("fargona-jamoat-salomatligi-tibbiyot-instituti", "Farg'ona jamoat salomatligi tibbiyot instituti", "davlat", "Farg'ona"),
  u("fargona-politexnika-instituti", "Farg'ona politexnika instituti", "davlat", "Farg'ona"),
  u("fargonadagi-koreya-xalqaro-universiteti", "Farg'onadagi Koreya xalqaro universiteti", "nodavlat", "Farg'ona"),
  u("kokand-university", "Kokand university", "nodavlat", "Farg'ona"),
  u("latviyaning-axborot-tizimlari-menejmenti-oliy-maktabi-fargon", "Latviyaning Axborot tizimlari menejmenti oliy maktabi Farg'ona filiali", "nodavlat", "Farg'ona"),
  u("ozbekiston-davlat-jismoniy-tarbiya-va-sport-universiteti-far", "O'zbekiston davlat jismoniy tarbiya va sport universiteti Farg'ona filiali", "davlat", "Farg'ona"),
  u("ozbekiston-davlat-sanat-va-madaniyat-institutining-fargona-m", "O'zbekiston davlat san'at va madaniyat institutining Farg'ona mintaqaviy filiali", "davlat", "Farg'ona"),
  u("qoqon-davlat-universiteti", "Qo'qon davlat universiteti", "davlat", "Farg'ona"),
  u("jizzax-davlat-pedagogika-universiteti", "Jizzax davlat pedagogika universiteti", "davlat", "Jizzax"),
  u("jizzax-politexnika-instituti", "Jizzax politexnika instituti", "davlat", "Jizzax"),
  u("mirzo-ulugbek-nomidagi-ozbekiston-milliy-universitetining-ji", "Mirzo Ulug'bek nomidagi O'zbekiston Milliy universitetining Jizzax filiali", "davlat", "Jizzax"),
  u("qozon-federal-universitetining-jizzax-filiali", "Qozon federal universitetining Jizzax filiali", "nodavlat", "Jizzax"),
  u("namangan-davlat-chet-tillari-instituti", "Namangan davlat chet tillari instituti", "davlat", "Namangan"),
  u("namangan-davlat-pedagogika-instituti", "Namangan davlat pedagogika instituti", "davlat", "Namangan"),
  u("namangan-davlat-texnika-universiteti", "Namangan davlat texnika universiteti", "davlat", "Namangan"),
  u("namangan-davlat-universiteti", "Namangan davlat universiteti", "davlat", "Namangan"),
  u("namangan-muhandislik-qurilish-instituti", "Namangan muhandislik-qurilish instituti", "davlat", "Namangan"),
  u("namangan-muhandislik-texnologiya-instituti", "Namangan muhandislik-texnologiya instituti", "davlat", "Namangan"),
  u("namangan-toqimachilik-sanoati-instituti", "Namangan to'qimachilik sanoati instituti", "davlat", "Namangan"),
  u("navoiy-davlat-konchilik-va-texnologiyalar-universiteti", "Navoiy davlat konchilik va texnologiyalar universiteti", "davlat", "Navoiy"),
  u("navoiy-davlat-universiteti", "Navoiy davlat universiteti", "davlat", "Navoiy"),
  u("navoiy-innovatsiyalar-instituti", "Navoiy innovatsiyalar instituti", "nodavlat", "Navoiy"),
  u("toshkent-axborot-texnologiyalari-universiteti-zarafshon-faku", "Toshkent axborot texnologiyalari universiteti Zarafshon fakulteti", "davlat", "Navoiy"),
  u("qarshi-davlat-texnika-universiteti", "Qarshi davlat texnika universiteti", "davlat", "Qashqadaryo"),
  u("qarshi-davlat-texnika-universiteti-shahrisabz-oziq-ovqat-muh", "Qarshi davlat texnika universiteti Shahrisabz oziq-ovqat muhandisligi fakulteti", "davlat", "Qashqadaryo"),
  u("qarshi-davlat-universiteti", "Qarshi davlat universiteti", "davlat", "Qashqadaryo"),
  u("qarshi-innovatsion-talim-universiteti", "Qarshi innovatsion ta'lim universiteti", "nodavlat", "Qashqadaryo"),
  u("qarshi-muhandislik-iqtisodiyot-instituti", "Qarshi Muhandislik-Iqtisodiyot Instituti", "davlat", "Qashqadaryo"),
  u("qarshi-xalqaro-universiteti", "Qarshi xalqaro universiteti", "nodavlat", "Qashqadaryo"),
  u("shahrisabz-davlat-pedagogika-instituti", "Shahrisabz davlat pedagogika instituti", "davlat", "Qashqadaryo"),
  u("tiqxmmi-milliy-tadqiqot-universitetining-qarshi-irrigatsiya", "TIQXMMI\" Milliy tadqiqot universitetining Qarshi irrigatsiya va agrotexnologiyalar instituti", "davlat", "Qashqadaryo"),
  u("toshkent-kimyo-texnologiya-instituti-shahrisabz-filiali", "Toshkent kimyo-texnologiya instituti Shahrisabz filiali", "davlat", "Qashqadaryo"),
  u("ajiniyoz-nomidagi-nukus-davlat-pedagogika-instituti", "Ajiniyoz nomidagi Nukus davlat pedagogika instituti", "davlat", "Qoraqalpog'iston"),
  u("berdaq-nomidagi-qoraqalpoq-davlat-universiteti", "Berdaq nomidagi Qoraqalpoq davlat universiteti", "davlat", "Qoraqalpog'iston"),
  u("muhammad-al-xorazmiy-nomidagi-toshkent-axborot-texnologiyala", "Muhammad al-Xorazmiy nomidagi Toshkent axborot texnologiyalari universiteti Nukus filiali", "davlat", "Qoraqalpog'iston"),
  u("navoiy-davlat-konchilik-va-texnologiyalar-universiteti-huzur", "Navoiy davlat konchilik va texnologiyalar universiteti huzuridagi Nukus konchilik instituti", "davlat", "Qoraqalpog'iston"),
  u("nukus-davlat-pedagogika-instituti-ellikqala-fakulteti", "Nukus davlat pedagogika instituti Ellikqal'a fakulteti", "davlat", "Qoraqalpog'iston"),
  u("nukus-davlat-texnika-universiteti", "Nukus davlat texnika universiteti", "davlat", "Qoraqalpog'iston"),
  u("nukus-innovatsion-instituti", "Nukus innovatsion instituti", "nodavlat", "Qoraqalpog'iston"),
  u("ozbekiston-davlat-jismoniy-tarbiya-va-sport-universiteti-nuk", "O'zbekiston davlat jismoniy tarbiya va sport universiteti Nukus filiali", "davlat", "Qoraqalpog'iston"),
  u("ozbekiston-davlat-konservatoriyasi-nukus-filiali", "O'zbekiston davlat konservatoriyasi Nukus filiali", "davlat", "Qoraqalpog'iston"),
  u("ozbekiston-davlat-sanat-va-madaniyat-instituti-nukus-filiali", "O'zbekiston davlat san'at va madaniyat instituti Nukus filiali", "davlat", "Qoraqalpog'iston"),
  u("qoraqalpogiston-qishloq-xojaligi-va-agrotexnologiyalar-insti", "Qoraqalpog'iston qishloq xo'jaligi va agrotexnologiyalar instituti", "davlat", "Qoraqalpog'iston"),
  u("qoraqalpogiston-tibbiyot-instituti", "Qoraqalpog'iston tibbiyot instituti", "davlat", "Qoraqalpog'iston"),
  u("qoraqalpoq-davlat-universiteti-chimboy-fakulteti", "Qoraqalpoq davlat universiteti Chimboy fakulteti", "davlat", "Qoraqalpog'iston"),
  u("qoraqalpoq-davlat-universiteti-qongirot-fakulteti", "Qoraqalpoq davlat universiteti Qo'ng'irot fakulteti", "davlat", "Qoraqalpog'iston"),
  u("samarqand-davlat-veterinariya-meditsinasi-chorvachilik-va-bi", "Samarqand davlat veterinariya meditsinasi, chorvachilik va biotexnologiyalar universiteti Nukus filiali", "davlat", "Qoraqalpog'iston"),
  u("toshkent-davlat-iqtisodiyot-universiteti-tortkol-fakulteti", "Toshkent davlat iqtisodiyot universiteti To'rtko'l fakulteti", "davlat", "Qoraqalpog'iston"),
  u("ipak-yoli-turizm-va-madaniy-meros-xalqaro-universiteti", "Ipak yo'li turizm va madaniy meros xalqaro universiteti", "davlat", "Samarqand"),
  u("kattaqorgon-davlat-pedagogika-instituti", "Kattaqo'rg'on davlat pedagogika instituti", "davlat", "Samarqand"),
  u("mirzo-ulugbek-nomidagi-samarqand-davlat-arxitektura-qurilish", "Mirzo Ulug'bek nomidagi Samarqand davlat arxitektura-qurilish universiteti", "davlat", "Samarqand"),
  u("samarqand-agroinnovatsiyalar-va-tadqiqotlar-instituti", "Samarqand agroinnovatsiyalar va tadqiqotlar instituti", "davlat", "Samarqand"),
  u("samarqand-davlat-chet-tillar-instituti", "Samarqand davlat chet tillar instituti", "davlat", "Samarqand"),
  u("samarqand-davlat-chet-tillar-instituti-narpay-xorijiy-tillar", "Samarqand davlat chet tillar instituti Narpay \"Xorijiy tillar\" fakulteti", "davlat", "Samarqand"),
  u("samarqand-davlat-chet-tillar-instituti-payariq-xorijiy-tilla", "Samarqand davlat chet tillar instituti Payariq \"Xorijiy tillar\" fakulteti", "davlat", "Samarqand"),
  u("samarqand-davlat-pedagogika-instituti", "Samarqand davlat pedagogika instituti", "davlat", "Samarqand"),
  u("samarqand-davlat-tibbiyot-universiteti", "Samarqand davlat tibbiyot universiteti", "davlat", "Samarqand"),
  u("samarqand-davlat-universitetining-agrobiotexnologiyalar-va-o", "Samarqand davlat universitetining Agrobiotexnologiyalar va oziq-ovqat xavfsizligi instituti", "davlat", "Samarqand"),
  u("samarqand-davlat-universitetining-denov-tadbirkorlik-va-peda", "Samarqand davlat universitetining Denov tadbirkorlik va pedagogika instituti", "davlat", "Samarqand"),
  u("samarqand-davlat-veterinariya-meditsinasi-chorvachilik-v-2", "Samarqand davlat veterinariya meditsinasi, chorvachilik va biotexnologiyalar universiteti", "davlat", "Samarqand"),
  u("samarqand-davlat-veterinariya-meditsinasi-chorvachilik-v-3", "Samarqand davlat veterinariya meditsinasi, chorvachilik va biotexnologiyalar universiteti Toshkent filiali", "davlat", "Samarqand"),
  u("samarqand-iqtisodiyot-va-servis-instituti", "Samarqand iqtisodiyot va servis instituti", "davlat", "Samarqand"),
  u("samarqand-xalqaro-texnologiya-universiteti", "Samarqand xalqaro texnologiya universiteti", "nodavlat", "Samarqand"),
  u("sharof-rashidov-nomidagi-samarqand-davlat-universiteti", "Sharof Rashidov nomidagi Samarqand davlat universiteti", "davlat", "Samarqand"),
  u("toshkent-axborot-texnologiyalari-universiteti-samarqand-fili", "Toshkent axborot texnologiyalari universiteti Samarqand filiali", "davlat", "Samarqand"),
  u("toshkent-davlat-iqtisodiyot-universiteti-samarqand-filiali", "Toshkent davlat iqtisodiyot universiteti Samarqand filiali", "davlat", "Samarqand"),
  u("turon-zarmed-universiteti", "Turon Zarmed universiteti", "nodavlat", "Samarqand"),
  u("guliston-davlat-pedagogika-instituti", "Guliston davlat pedagogika instituti", "davlat", "Sirdaryo"),
  u("guliston-davlat-universiteti", "Guliston davlat universiteti", "davlat", "Sirdaryo"),
  u("toshkent-kimyo-texnologiya-instituti-yangiyer-filiali", "Toshkent kimyo-texnologiya instituti Yangiyer filiali", "davlat", "Sirdaryo"),
  u("termiz-agrotexnologiyalar-va-innovatsion-rivojlanish-institu", "Termiz agrotexnologiyalar va innovatsion rivojlanish instituti", "davlat", "Surxondaryo"),
  u("termiz-davlat-muhandislik-va-agrotexnologiyalar-universiteti", "Termiz davlat muhandislik va agrotexnologiyalar universiteti", "davlat", "Surxondaryo"),
  u("termiz-davlat-pedagogika-instituti", "Termiz davlat pedagogika instituti", "davlat", "Surxondaryo"),
  u("termiz-davlat-universiteti", "Termiz davlat universiteti", "davlat", "Surxondaryo"),
  u("termiz-iqtisodiyot-va-servis-universiteti", "Termiz iqtisodiyot va servis universiteti", "nodavlat", "Surxondaryo"),
  u("termiz-muhandislik-texnologiya-instituti", "Termiz muhandislik-texnologiya instituti", "davlat", "Surxondaryo"),
  u("toshkent-davlat-tibbiyot-universiteti-termiz-filiali", "Toshkent davlat tibbiyot universiteti Termiz filiali", "davlat", "Surxondaryo"),
  u("chirchiq-davlat-pedagogika-universiteti", "Chirchiq davlat pedagogika universiteti", "davlat", "Toshkent viloyati"),
  u("misis-milliy-tadqiqot-texnologiya-universitetining-olmaliq-f", "MISiS\" Milliy tadqiqot texnologiya universitetining Olmaliq filiali", "nodavlat", "Toshkent viloyati"),
  u("ozbekiston-davlat-jahon-tillari-universiteti-angren-fakultet", "O'zbekiston davlat jahon tillari universiteti Angren fakulteti", "davlat", "Toshkent viloyati"),
  u("olmaliq-davlat-texnika-instituti", "Olmaliq davlat texnika instituti", "davlat", "Toshkent viloyati"),
  u("toshkent-davlat-tibbiyot-universiteti-chirchiq-filiali", "Toshkent davlat tibbiyot universiteti Chirchiq filiali", "davlat", "Toshkent viloyati"),
  u("abu-rayhon-beruniy-nomidagi-urganch-davlat-universiteti", "Abu Rayhon Beruniy nomidagi Urganch davlat universiteti", "davlat", "Xorazm"),
  u("muhammad-al-xorazmiy-nomidagi-toshkent-axborot-texnologi-2", "Muhammad al-Xorazmiy nomidagi Toshkent axborot texnologiyalari universiteti", "davlat", "Xorazm"),
  u("muhammad-al-xorazmiy-nomidagi-toshkent-axborot-texnologi-3", "Muhammad al-Xorazmiy nomidagi Toshkent axborot texnologiyalari universiteti Farg'ona filiali", "davlat", "Xorazm"),
  u("muhammad-al-xorazmiy-nomidagi-toshkent-axborot-texnologi-4", "Muhammad al-Xorazmiy nomidagi Toshkent axborot texnologiyalari universiteti Nurafshon filiali", "davlat", "Xorazm"),
  u("muhammad-al-xorazmiy-nomidagi-toshkent-axborot-texnologi-5", "Muhammad al-Xorazmiy nomidagi Toshkent axborot texnologiyalari universiteti Qarshi filiali", "davlat", "Xorazm"),
  u("ozbekiston-davlat-xoreografiya-akademiyasi-urganch-filiali", "O'zbekiston davlat xoreografiya akademiyasi Urganch filiali", "davlat", "Xorazm"),
  u("toshkent-axborot-texnologiyalari-universiteti-urganch-filial", "Toshkent axborot texnologiyalari universiteti Urganch filiali", "davlat", "Xorazm"),
  u("toshkent-tibbiyot-akademiyasi-urganch-filiali", "Toshkent tibbiyot akademiyasi Urganch filiali", "davlat", "Xorazm"),
  u("urganch-davlat-pedagogika-instituti", "Urganch davlat pedagogika instituti", "davlat", "Xorazm"),
  u("urganch-innovatsion-universiteti", "Urganch innovatsion universiteti", "nodavlat", "Xorazm"),
];

const byId = new Map(UNIVERSITIES.map((x) => [x.id, x]));

export const universityById = (id: string | null | undefined) => (id ? byId.get(id) : undefined);

const fold = (s: string) => s.toLowerCase().replace(/[ʻʼ‘’`']/g, "").replace(/\s+/g, " ");

/** Nom bo'yicha qidiruv: har bir so'z nomda uchrashi kerak ("tatu samarqand" ham topadi). */
export function searchUniversities(query: string, limit = 50): University[] {
  const words = fold(query).split(" ").filter(Boolean);
  if (!words.length) return UNIVERSITIES.slice(0, limit);
  return UNIVERSITIES.filter((x) => {
    const hay = fold(`${x.name} ${x.region}`);
    return words.every((w) => hay.includes(w));
  }).slice(0, limit);
}
